import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {openDatabase} from '../src/database.mjs';import {createApplication} from '../src/app.mjs';import {moderated,validateAttachment,SUPPORT_DEFAULTS,validateSupportConfig} from '../src/support-policy.mjs';
async function setup(t){const db=openDatabase(':memory:'),folder=mkdtempSync(join(tmpdir(),'elite-support-test-')),app=createApplication({db,key:randomBytes(32),env:{APP_ORIGIN:'http://localhost:3000',SUPPORT_FILES_PATH:folder},gateway:null,mailer:null});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;t.after(async()=>{await app.close();db.close();rmSync(folder,{recursive:true,force:true});});
 const client=()=>{let cookie='',csrf='';return {async call(path,method='GET',body,extra={}){const binary=Buffer.isBuffer(body);const r=await fetch(base+path,{method,headers:{Cookie:cookie,...(method==='GET'?{}:{'Content-Type':binary?'text/plain':'application/json','X-CSRF-Token':csrf}),...extra},body:method==='GET'?undefined:binary?body:JSON.stringify(body||{})});if(r.headers.getSetCookie().length)cookie=r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');const json=r.headers.get('Content-Type')?.includes('application/json');const data=json?await r.json():await r.text();csrf=data?.csrf||csrf;return {status:r.status,data,headers:r.headers};}};};
 const customer=client(),other=client(),admin=client();for(const [c,name]of [[customer,'Customer'],[other,'Other'],[admin,'Agent']]){const r=await c.call('/api/auth/signup','POST',{email:name+'@example.test',name,password:'Support test password 42!'});assert.equal(r.status,201);c.user=r.data.user;}
 db.prepare("UPDATE users SET role='admin' WHERE id=?").run(admin.user.id);return {db,customer,other,admin};}
const prefix='/api/support/workspace';
test('support: authorization, exactly-once messages, notes, read markers and assignment',async t=>{const {customer,other,admin}=await setup(t),chat=(await customer.call(prefix,'POST',{category:'MT5 connection'})).data.id;
 assert.equal((await other.call(`${prefix}/${chat}`)).status,404);
 assert.equal((await other.call(`${prefix}/${chat}/heartbeat`,'POST',{tabId:randomUUID(),active:true})).status,404);
 const payload={message:'My MT5 connection is failing.',clientId:randomUUID(),attachments:[]};assert.equal((await customer.call(`${prefix}/${chat}/send`,'POST',payload)).status,200);assert.equal((await customer.call(`${prefix}/${chat}/send`,'POST',payload)).data.duplicate,true);
 let history=(await admin.call(`${prefix}/${chat}`)).data;assert.equal(history.messages.length,1);assert.equal((await admin.call(prefix)).data.conversations[0].unread,1);
 assert.equal((await customer.call(`${prefix}/${chat}/note`,'POST',{message:'Forbidden'})).status,403);assert.equal((await admin.call(`${prefix}/${chat}/note`,'POST',{message:'Private agent note.'})).status,200);assert.ok(!(await customer.call(`${prefix}/${chat}`)).data.notes);assert.equal((await admin.call(`${prefix}/${chat}`)).data.notes[0].body,'Private agent note.');
 assert.equal((await customer.call(`${prefix}/${chat}/update`,'POST',{assigned_to:admin.user.id})).status,403);assert.equal((await admin.call(`${prefix}/${chat}/update`,'POST',{assigned_to:admin.user.id,priority:'High',stage:'waiting'})).status,200);
 assert.equal((await admin.call(`${prefix}/${chat}/read`,'POST',{cursor:history.messages[0].support_seq})).status,200);assert.equal((await customer.call(`${prefix}/${chat}`)).data.peerRead,history.messages[0].support_seq);assert.equal((await admin.call(prefix)).data.conversations[0].unread,0);
 assert.equal((await admin.call(`${prefix}/${chat}/update`,'POST',{stage:'resolved'})).status,200);assert.equal((await customer.call(`${prefix}/${chat}/send`,'POST',{...payload,clientId:randomUUID()})).status,409);assert.equal((await customer.call(`${prefix}/${chat}/update`,'POST',{rating:5})).status,200);assert.equal((await customer.call(`${prefix}/${chat}/update`,'POST',{stage:'open'})).status,200);
});
test('support: heartbeat confirmation, typing expiry, away, offline and unassigned status',async t=>{const {db,customer,admin}=await setup(t),chat=(await customer.call(prefix,'POST',{})).data.id,tabId=randomUUID();assert.equal((await customer.call(`${prefix}/${chat}`)).data.presence.status,'unavailable');await admin.call(`${prefix}/${chat}/update`,'POST',{assigned_to:admin.user.id});await admin.call(`${prefix}/${chat}/heartbeat`,'POST',{tabId,active:true,typing:true});let p=(await customer.call(`${prefix}/${chat}`)).data.presence;assert.equal(p.status,'online');assert.equal(p.typing,true);
 const row=JSON.parse(db.prepare('SELECT value FROM support_state WHERE id=?').get(chat).value);const state=Object.values(row.presence)[0];state.active=Date.now()-125000;state.typing=Date.now()-6000;db.prepare('UPDATE support_state SET value=? WHERE id=?').run(JSON.stringify(row),chat);p=(await customer.call(`${prefix}/${chat}`)).data.presence;assert.equal(p.status,'away');assert.equal(p.typing,false);state.seen=Date.now()-46000;db.prepare('UPDATE support_state SET value=? WHERE id=?').run(JSON.stringify(row),chat);assert.equal((await customer.call(`${prefix}/${chat}`)).data.presence.status,'offline');
});
test('support: 20k text, moderation, retries, durable history pagination and rate limits',async t=>{const {db,customer,admin}=await setup(t),chat=(await customer.call(prefix,'POST',{})).data.id;
 const send=message=>customer.call(`${prefix}/${chat}/send`,'POST',{message,clientId:randomUUID(),attachments:[]});assert.equal((await send('x'.repeat(20000))).status,200);assert.equal((await send('x'.repeat(20001))).status,400);assert.equal((await send('ｆｕｃｋ')).status,422);assert.equal((await send('Scunthorpe Capital, asset classes and broker slippage are legitimate.')).status,200);assert.equal((await send('This bot is awful and the payment is broken!')).status,200);
 for(let i=0;i<75;i++)db.prepare('INSERT INTO messages VALUES(?,?,?,?,?)').run(randomUUID(),chat,'admin','Fixture '+i,Date.now());let d=(await customer.call(`${prefix}/${chat}`)).data;assert.equal(d.messages.length,60);const earlier=(await customer.call(`${prefix}/${chat}?before=${d.messages[0].support_seq}`)).data;assert.ok(earlier.messages.length>0);const missed=(await customer.call(`${prefix}/${chat}?after=${earlier.messages[0].support_seq}`)).data;assert.equal(missed.messages[0].support_seq,earlier.messages[0].support_seq+1);assert.equal(missed.messages.length,60);
 for(let i=0;i<28;i++)await send('Rate fixture');assert.equal((await send('Too many')).status,429);
 assert.equal((await customer.call(prefix+'/config','POST',SUPPORT_DEFAULTS)).status,403);assert.equal((await admin.call(prefix+'/config','POST',{...SUPPORT_DEFAULTS,words:['abuseword']})).status,200);assert.equal((await admin.call(prefix)).data.config.words[0],'abuseword');
});
test('support: authenticated private attachment upload, ownership, signatures and safe download',async t=>{const {customer,other,admin}=await setup(t),chat=(await customer.call(prefix,'POST',{})).data.id,raw=Buffer.from('A private support document.');const uploaded=await customer.call(`${prefix}/${chat}/attachments`,'POST',raw,{'X-File-Name':'support.txt'});assert.equal(uploaded.status,201,JSON.stringify(uploaded.data));const id=uploaded.data.id;assert.equal((await other.call(`${prefix}/${chat}/attachments/${id}`)).status,404);assert.equal((await admin.call(`${prefix}/${chat}/attachments/${id}`)).status,404);await customer.call(`${prefix}/${chat}/send`,'POST',{message:'',clientId:randomUUID(),attachments:[id]});const downloaded=await admin.call(`${prefix}/${chat}/attachments/${id}`);assert.equal(downloaded.status,200);assert.match(downloaded.headers.get('Content-Disposition'),/^attachment/);assert.equal(downloaded.headers.get('X-Content-Type-Options'),'nosniff');assert.equal(downloaded.data,raw.toString());assert.equal((await customer.call(`${prefix}/${chat}/attachments/${id}`,'DELETE')).status,403);
 assert.equal((await customer.call(`${prefix}/${chat}/attachments`,'POST',Buffer.from('<html><script>evil</script></html>'),{'X-File-Name':'fake.txt'})).status,400);assert.equal((await customer.call(`${prefix}/${chat}/attachments`,'POST',raw,{'X-File-Name':'fake.png','Content-Type':'image/png'})).status,400);
});
test('support file policy rejects malformed Office ZIPs, disguised HTML and unsafe names',()=>{assert.equal(moderated('Scunthorpe forex asset broker',SUPPORT_DEFAULTS.words),false);assert.equal(moderated('FUCK!',SUPPORT_DEFAULTS.words),true);assert.throws(()=>validateAttachment(Buffer.from('PKfake'),'test.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'));assert.throws(()=>validateAttachment(Buffer.from('x'),'../x.txt','text/plain'));assert.throws(()=>validateAttachment(Buffer.from('x'),'x.txt','text/plain',0));assert.throws(()=>validateSupportConfig({...SUPPORT_DEFAULTS,words:['bad word']}));});
function zipFixture(entries){let offset=0;const data=[],directory=[];function crc(b){let c=0xffffffff;for(const byte of b){c^=byte;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}for(const [name,content]of entries){const n=Buffer.from(name),b=Buffer.from(content),header=Buffer.alloc(30),central=Buffer.alloc(46),checksum=crc(b);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt32LE(checksum,14);header.writeUInt32LE(b.length,18);header.writeUInt32LE(b.length,22);header.writeUInt16LE(n.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(checksum,16);central.writeUInt32LE(b.length,20);central.writeUInt32LE(b.length,24);central.writeUInt16LE(n.length,28);central.writeUInt32LE(offset,42);data.push(header,n,b);directory.push(central,n);offset+=30+n.length+b.length;}const dir=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(dir.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...data,dir,end]);}
test('support signatures accept Office documents and reject disguised or macro-enabled packages',()=>{for(const [ext,type,entry,mark] of [['docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document','word/document.xml','wordprocessingml'],['xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','xl/workbook.xml','spreadsheetml']]){const files=[['[Content_Types].xml',`<Types>${mark}</Types>`],[entry,'<document>Isolated fixture</document>']];const file=zipFixture(files);assert.equal(validateAttachment(file,`fixture.${ext}`,type).mime,type);assert.throws(()=>validateAttachment(zipFixture([...files,['word/vbaProject.bin','macro']]),`fixture.${ext}`,type),/macro/);assert.throws(()=>validateAttachment(file.subarray(0,20),`fixture.${ext}`,type));}assert.equal(validateAttachment(Buffer.from('symbol,issue\nXAUUSD,connection\n'),'fixture.csv','text/csv').mime,'text/csv');assert.throws(()=>validateAttachment(Buffer.from('%PDF-1.7\n'), 'invalid.pdf','application/pdf'));});
