// Isolated two-session browser verification against the real SQLite adapter. All identities are fixtures.
import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApplication} from '../src/app.mjs';import {openDatabase} from '../src/database.mjs';import {digest,hashPassword} from '../src/security.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const db=openDatabase(':memory:'),folder=mkdtempSync(join(tmpdir(),'elite-support-browser-')),base='http://127.0.0.1:4395';
const app=createApplication({db,key:randomBytes(32),gateway:null,mailer:null,env:{APP_ORIGIN:base,SUPPORT_FILES_PATH:folder}});await new Promise(r=>app.server.listen(4395,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||chromium.executablePath(),args:['--no-sandbox']});mkdirSync('test-results',{recursive:true});const contexts=[],errors=[];
async function session(name,role){const uid=randomUUID(),token=randomUUID(),csrf=randomUUID();db.prepare('INSERT INTO users(id,email,name,password_hash,role,referral_code,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,`${name}@example.test`,name,await hashPassword('Support fixture password!'),role,randomUUID(),Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?)').run(digest(token),uid,csrf,1,Date.now()+86400000,Date.now());const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);await context.addCookies([{name:'elite_session',value:token,url:base}]);await context.addInitScript(()=>localStorage.setItem('elite-supabase-session',JSON.stringify({access_token:'isolated-browser-fixture',expires_at:Date.now()/1000+3600})));await context.route('**/api/**',async route=>{if(route.request().method()==='GET')return route.continue();const r=await route.fetch({headers:{...route.request().headers(),'x-csrf-token':csrf}});return route.fulfill({response:r});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));return {page,context,uid};}
async function waitWorkspace(page,path){await page.goto(base+path);await page.locator('.support-workspace').waitFor();await page.locator('#app-opening').waitFor({state:'hidden'});}
const customer=await session('QA customer','user'),admin=await session('QA agent','admin');
try{
 await waitWorkspace(customer.page,'/support');await customer.page.locator('[data-chat="new"]').first().click();await customer.page.locator('#modal select').selectOption('MT5 connection');await customer.page.locator('#modal button[type="submit"]').click();await customer.page.locator('[data-composer]').waitFor();await customer.page.locator('[data-composer]').fill('Isolated fixture: my MT5 connection needs attention.');await customer.page.locator('[data-compose] [type="submit"]').click();await customer.page.locator('[data-timeline]').getByText('Isolated fixture: my MT5 connection needs attention.',{exact:true}).waitFor();
 await waitWorkspace(admin.page,'/admin/support');await admin.page.locator('[data-composer]').waitFor();await admin.page.locator('[data-chat="details"]').first().click();await admin.page.locator('[data-support-setting="assigned_to"]').selectOption(admin.uid);await customer.page.locator('.support-participant h2').filter({hasText:'QA agent'}).waitFor({timeout:12000});await admin.page.locator('[data-chat="details"]').last().click();
 await admin.page.locator('[data-composer]').fill('I am checking the error with you. Please keep your passwords private.');await customer.page.locator('[data-typing]:not([hidden])').waitFor({timeout:10000});await admin.page.locator('[data-compose] [type="submit"]').click();await customer.page.locator('[data-timeline]').getByText('I am checking the error with you. Please keep your passwords private.',{exact:true}).waitFor({timeout:10000});await admin.page.locator('[data-receipt]').filter({hasText:'Read'}).waitFor({timeout:10000});
 await admin.page.locator('[data-chat="note"]').first().click();await admin.page.locator('[data-composer]').fill('PRIVATE fixture note');await admin.page.locator('[data-compose] [type="submit"]').click();await admin.page.locator('[data-chat="details"]').first().click();await admin.page.locator('.support-notes').getByText('PRIVATE fixture note',{exact:true}).waitFor();assert.equal(await customer.page.getByText('PRIVATE fixture note',{exact:true}).count(),0);await admin.page.locator('[data-chat="details"]').last().click();await admin.page.locator('[data-chat="note"]').first().click();
 await customer.page.locator('[data-files]').setInputFiles({name:'fixture.txt',mimeType:'text/plain',buffer:Buffer.from('Private fixture attachment')});await customer.page.getByText('Ready',{exact:true}).waitFor();await customer.page.locator('[data-composer]').fill('Document attached.');await customer.page.locator('[data-compose] [type="submit"]').click();await admin.page.getByText('fixture.txt',{exact:true}).waitFor({timeout:10000});
 await customer.page.locator('[data-files]').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aRuoAAAAASUVORK5CYII=','base64')});await customer.page.getByText('Ready',{exact:true}).waitFor();await customer.page.locator('[data-compose] [type="submit"]').click();await customer.page.locator('[data-chat="file"][data-name="fixture.png"]').click();await customer.page.locator('#modal .support-image-viewer').waitFor();await customer.page.keyboard.press('Escape');await customer.page.locator('#modal').waitFor({state:'hidden'});
 await customer.page.locator('[data-composer]').fill('fuck');await customer.page.locator('[data-compose] [type="submit"]').click();await customer.page.locator('[data-chat-error]').filter({hasText:'blocked word'}).waitFor();assert.equal(await customer.page.locator('[data-composer]').inputValue(),'fuck');await customer.page.locator('[data-composer]').fill('Draft survives navigation.');await customer.page.goto(base+'/account');await waitWorkspace(customer.page,'/support');await customer.page.locator('[data-composer]').waitFor();assert.equal(await customer.page.locator('[data-composer]').inputValue(),'Draft survives navigation.');
 await customer.context.setOffline(true);await customer.page.locator('[data-sync]:not([hidden])').waitFor();assert.equal(await customer.page.locator('[data-composer]').inputValue(),'Draft survives navigation.');await customer.context.setOffline(false);await customer.page.locator('[data-sync]').waitFor({state:'hidden',timeout:15000});
 for(const theme of ['dark','light'])for(const width of [360,390,768,1440]){
  await customer.page.setViewportSize({width,height:900});await customer.page.evaluate(t=>document.body.classList.toggle('light',t==='light'),theme);await customer.page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));document.querySelector('#toast')?.classList.remove('visible');});const result=await customer.page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,composer:document.querySelector('[data-compose]').getBoundingClientRect().bottom,nav:document.querySelector('.bottom-nav').getBoundingClientRect().top,navVisible:getComputedStyle(document.querySelector('.bottom-nav')).display!=='none'}));assert.equal(result.overflow,false,`horizontal overflow ${width} ${theme}`);if(result.navVisible)assert.ok(result.composer<=result.nav+1,`composer overlap ${width} ${theme}: ${JSON.stringify(result)}`);await customer.page.screenshot({path:`test-results/support-${theme}-${width}.png`,animations:'disabled'});
 }
 await customer.page.setViewportSize({width:390,height:900});await customer.page.locator('[data-chat="back"]').click();await customer.page.locator('.support-thread').first().click();await customer.page.locator('[data-composer]').waitFor();await customer.page.locator('[data-composer]').fill('x'.repeat(20000));assert.equal(await customer.page.locator('[data-counter]').textContent(),'20,000 / 20,000');await customer.page.locator('[data-chat="expand"]').click();await customer.page.screenshot({path:'test-results/support-long-mobile.png'});
 assert.deepEqual(errors,[]);console.log('Support browser passed: two sessions, typing, replies, reads, notes, private document upload, moderation, drafts, offline recovery, 360/390/768/1440 both themes, no overflow/overlap.');
}catch(e){console.log('QA errors:',errors);await customer.page.screenshot({path:'test-results/support-browser-failure.png'});console.log((await customer.page.locator('body').innerText()).slice(-6000));throw e;}finally{for(const c of contexts)await c.close();await browser.close();await app.close();db.close();rmSync(folder,{recursive:true,force:true});}
