import { blogPosts } from './blog-content.mjs';

const origin = 'https://elitetradee.vercel.app';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = value => JSON.stringify(value).replace(/</g,'\\u003c');
export const wordCount = post => post.sections.map(section => section[1]).join(' ').trim().split(/\s+/).length;
const readingTime = post => Math.max(1,Math.ceil(wordCount(post)/200));
const brand = '<a href="/" class="brand site-brand"><img class="brand-logo" src="/favicon.svg?v=eb1989" alt="EliteBot" width="104" height="48" decoding="async"></a>';
const menuIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg>';
const themeIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M20 14.2A8 8 0 0 1 9.8 4a8 8 0 1 0 10.2 10.2Z"/></svg>';
const nav = '<a href="/#platform">Platform</a><a href="/#workflow">How it works</a><a href="/#security">Security</a><a href="/#pricing">Access</a><a href="/blog" aria-current="page">Blog</a>';
const header = '<header class="marketing-header"><div class="marketing-nav">'+brand+'<nav class="marketing-links" aria-label="Marketing navigation">'+nav+'</nav><div class="marketing-actions"><button type="button" class="icon ghost" data-blog-theme aria-label="Toggle light and dark theme">'+themeIcon+'</button><a class="nav-login" href="/login">Sign in</a><a class="marketing-cta small" href="/signup">Get started</a><details class="public-menu"><summary aria-label="Navigation menu">'+menuIcon+'</summary><nav aria-label="Mobile site navigation">'+nav+'<a href="/support">Support</a><a href="/login">Sign in</a><a href="/signup">Create account</a></nav></details></div></div></header>';
const footer = '<footer class="marketing-footer"><div class="footer-grid"><div><div class="footer-brand">'+brand+'</div><p>Tools for managing MT5 connections, automation controls, account access, payments, and support from one focused workspace.</p></div><div><strong>Platform</strong><a href="/#platform">Overview</a><a href="/#security">Security</a><a href="/blog">Blog</a><a href="/support">Support</a><a href="/signup">Create account</a></div><div><strong>Legal</strong><a href="/terms">Terms of Service</a><a href="/privacy">Privacy Policy</a><a href="/risk-disclosure">Risk Disclosure</a><a href="/refund-policy">Refund Policy</a><a href="/cookies">Cookie Policy</a></div></div><div class="footer-bottom"><span>© 2026 Elite Bot. All rights reserved.</span><span>Trading involves substantial risk. No performance is guaranteed.</span></div></footer>';
function page({title,description,path,body,schema=[],article=false,noindex=false}) {
  const canonical = origin+path;
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#131722"><meta name="robots" content="'+(noindex?'noindex,follow':'index,follow')+'"><title>'+esc(title)+'</title><meta name="description" content="'+esc(description)+'"><link rel="canonical" href="'+esc(canonical)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+esc(canonical)+'"><meta property="og:type" content="'+(article?'article':'website')+'"><meta property="og:site_name" content="EliteBot"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="'+esc(title)+'"><meta name="twitter:description" content="'+esc(description)+'">'+(article?'<meta property="article:published_time" content="2026-10-02">':'')+'<link rel="icon" href="/favicon.svg?v=eb1989"><link rel="preload" href="/fonts/dm-sans.woff" as="font" type="font/woff" crossorigin><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/auth.css"><link rel="stylesheet" href="/blog.css"><script type="module" src="/blog.js"></script>'+schema.map(s=>'<script type="application/ld+json">'+json(s)+'</script>').join('')+'</head><body class="blog-page"><a class="skip" href="#main">Skip to content</a>'+header+'<main id="main" class="blog-main" tabindex="-1">'+body+'</main>'+footer+'</body></html>';
}
const breadcrumb = post => ({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[
  {'@type':'ListItem',position:1,name:'Home',item:origin+'/'},
  {'@type':'ListItem',position:2,name:'Blog',item:origin+'/blog'},
  ...(post?[{'@type':'ListItem',position:3,name:post.title,item:origin+'/blog/'+post.slug}]:[])
]});
const cta = '<aside class="blog-cta" aria-label="Create an EliteBot account"><div><span class="blog-eyebrow">Your next step</span><h2>Bring your workflow into focus.</h2><p>Review MT5 connections, automation settings and account access in one workspace.</p></div><a class="marketing-cta" href="/signup">Create your account <span aria-hidden="true">↗</span></a></aside>';
const paragraphLink = '<a class="blog-inline-signup" href="/signup">Create an EliteBot account <span aria-hidden="true">↗</span></a>';
function card(post,index) {
 return '<article class="blog-card"><div class="blog-card-top"><span class="blog-category">'+esc(post.category)+'</span><span class="blog-number" aria-hidden="true">'+String(index+1).padStart(2,'0')+'</span></div><h2><a href="/blog/'+post.slug+'">'+esc(post.title)+'</a></h2><p>'+esc(post.description)+'</p><div class="blog-card-meta"><span>'+readingTime(post)+' min read</span><span>EliteBot Editorial</span></div><div class="blog-card-actions"><a class="blog-read" href="/blog/'+post.slug+'">Read guide <span aria-hidden="true">↗</span><span class="sr-only">: '+esc(post.title)+'</span></a><a href="/signup" class="blog-card-signup">Create account</a></div></article>';
}
function indexPage() {
 const title = 'EliteBot Blog | MT5 Automation, Risk Controls & Account Security';
 const description = 'Explore practical MT5 setup guides, trading bot risk controls, demo testing, secure account access and subscription workflows from EliteBot.';
 const body = '<section class="blog-intro"><div class="blog-eyebrow"><span class="blog-dot" aria-hidden="true"></span> The EliteBot journal</div><h1>A clearer way to<br>understand automation.</h1><p>Practical guides for your MT5 connections, risk settings and account security. Read with purpose. Test with care.</p><div class="blog-intro-actions"><a class="marketing-cta" href="/signup">Create your account</a><a class="marketing-secondary" href="#guides">Explore the guides <span aria-hidden="true">↓</span></a></div><div class="blog-topics" aria-label="Topics">'+[...new Set(blogPosts.map(p=>p.category))].map(t=>'<span>'+esc(t)+'</span>').join('')+'</div></section><section id="guides" class="blog-guides" aria-labelledby="guides-title"><div class="blog-section-head"><h2 id="guides-title">The practical library</h2><span>10 guides · Built around your workflow</span></div><div class="blog-grid">'+blogPosts.map(card).join('')+'</div></section>'+cta;
 const schema = [
 {'@context':'https://schema.org','@type':'Blog',name:'EliteBot Blog',description,url:origin+'/blog',inLanguage:'en',publisher:{'@type':'Organization',name:'EliteBot',url:origin+'/'},blogPost:blogPosts.map(p=>({'@type':'BlogPosting',headline:p.title,url:origin+'/blog/'+p.slug,datePublished:p.date}))},
 {'@context':'https://schema.org','@type':'ItemList',itemListElement:blogPosts.map((p,i)=>({'@type':'ListItem',position:i+1,url:origin+'/blog/'+p.slug,name:p.title}))},
 breadcrumb()
 ];
 return {status:200,html:page({title,description,path:'/blog',body,schema})};
}
function articlePage(post) {
 const index = blogPosts.indexOf(post);
 const related = blogPosts.filter(p=>p!==post && p.category===post.category);
 for (let n=1;related.length<3 && n<blogPosts.length;n++) {
  const candidate=blogPosts[(index+n)%blogPosts.length];
  if(candidate!==post&&!related.includes(candidate)) related.push(candidate);
 }
 const body = '<nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/blog">Blog</a><span aria-hidden="true">/</span><span>'+esc(post.category)+'</span></nav><header class="blog-article-header"><span class="blog-category">'+esc(post.category)+'</span><h1>'+esc(post.title)+'</h1><p class="blog-deck">'+esc(post.description)+'</p><div class="blog-byline"><span>By EliteBot Editorial</span><time datetime="'+post.date+'">October 2, 2026</time><span>'+readingTime(post)+' min read · '+wordCount(post)+' words</span></div></header><div class="blog-reading-layout"><aside class="blog-toc"><nav aria-label="On this page"><strong>On this page</strong><ol>'+post.sections.map((s,i)=>'<li><a href="#section-'+(i+1)+'">'+esc(s[0])+'</a></li>').join('')+'</ol></nav><a class="marketing-cta small" href="/signup">Create account</a></aside><article class="blog-article-body" aria-label="'+esc(post.title)+'">'+post.sections.map((s,i)=>'<section aria-labelledby="section-'+(i+1)+'"><h2 id="section-'+(i+1)+'">'+esc(s[0])+'</h2><p class="blog-content-paragraph">'+esc(s[1])+' '+paragraphLink+'</p></section>').join('')+'<div class="blog-article-notes"><p>Educational guidance from EliteBot Editorial. Trading involves substantial risk. Demo results and software settings do not guarantee live performance. Review the <a href="/risk-disclosure">risk disclosure</a> and the current capabilities shown in your workspace.</p>'+(post.sources.length?'<h2>Further reading</h2><ul>'+post.sources.map(([label,url])=>'<li><a href="'+esc(url)+'" rel="noopener noreferrer" target="_blank">'+esc(label)+' <span class="sr-only">(opens in a new tab)</span></a></li>').join('')+'</ul>':'')+'<div class="blog-hashtags" aria-label="Article hashtags">'+post.hashtags.map(t=>'<span>#'+esc(t)+'</span>').join('')+'</div><a class="blog-trends" href="https://trends.google.com/trends/explore?date=today%2012-m&amp;q='+encodeURIComponent(post.hashtags.map(t=>t.replace(/([a-z])([A-Z])/g,'$1 $2')).join(','))+'" target="_blank" rel="noopener noreferrer">Explore these topics on Google Trends <span class="sr-only">(opens in a new tab)</span><span aria-hidden="true">↗</span></a><small class="blog-trends-note">Explore current interest by region. No search-volume or ranking claims are made here.</small></div></article></div>'+cta+'<section class="blog-related" aria-labelledby="related-title"><div class="blog-section-head"><h2 id="related-title">Keep building your understanding</h2><a href="/blog">All guides <span aria-hidden="true">↗</span></a></div><div class="blog-grid">'+related.slice(0,3).map(p=>card(p,blogPosts.indexOf(p))).join('')+'</div></section>';
 const schema = [ {'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:post.description,url:origin+'/blog/'+post.slug,mainEntityOfPage:{'@type':'WebPage','@id':origin+'/blog/'+post.slug},datePublished:post.date,dateModified:post.date,author:{'@type':'Organization',name:'EliteBot Editorial',url:origin+'/blog'},publisher:{'@type':'Organization',name:'EliteBot',url:origin+'/'},articleSection:post.category,keywords:post.hashtags.join(', '),inLanguage:'en',wordCount:wordCount(post),isAccessibleForFree:true,articleBody:post.sections.map(s=>s[0]+'\n'+s[1]).join('\n\n')},breadcrumb(post)];
 return {status:200,html:page({title:post.title+' | EliteBot Blog',description:post.description,path:'/blog/'+post.slug,body,schema,article:true})};
}
export function renderBlogPage(path) {
 if(path!=='/blog'&&!path.startsWith('/blog/'))return null;
 if(path.endsWith('/')) {
  const clean=path.replace(/\/+$/,'');
  if(clean==='/blog'||blogPosts.some(p=>clean==='/blog/'+p.slug))return {status:308,location:clean};
 }
 if(path==='/blog')return indexPage();
 const post=blogPosts.find(p=>path==='/blog/'+p.slug);
 if(post)return articlePage(post);
 return {status:404,html:page({title:'Guide not found | EliteBot Blog',description:'This guide is unavailable. Browse the EliteBot blog for MT5 setup, risk controls and account security guides.',path:'/blog',noindex:true,body:'<section class="blog-intro"><span class="blog-eyebrow">404 · Guide not found</span><h1>Let’s get you back<br>to the library.</h1><p>This article address is unavailable. Explore our practical MT5 guides instead.</p><a class="marketing-cta" href="/blog">Browse all guides</a></section>'})};
}
